### ISSUE TITLE
OpenGL Widget Reference

### ISSUE THREAD

**Issue by snitchjinx** [alonrubintec/3DViewer#2]
Hello! Thank you for sharing this great repo!
I got a question in reading through the code.

In the UI layout the name of opengl widget is named "openGLWidget".
But in the [code](https://github.com/alonrubintec/3DViewer/blob/d30bc2da629944b715a7823515fab56fda5b7391/main.py#L16) "openGLWidget" is never refered, a new widget "QGLControllerWidget" is created instead.

Could you please help explain this?
Thank you for your consideration!

**Comment by alonrubintec** [comment]
Hello :)
Oh yeah the "openGLWidget" in the UI was something I worked with but didn't use. Instead, I created "QGLControllerWidget" in the code. To fix it, you can rename the widget in the QT Designer or modify the code.

**Comment by snitchjinx** [comment]
Thank you for your response!

I can see how to fix the name references. But I'm new to using OpenGL in PyQt and I don't quite understand how "QGLControllerWidget" is able to render models in place of "openGLWidget". Could you please help suggest which part of the code indicates the "openGLWidget" is replace by the "QGLControllerWidget"?
Thank you very much!

**Comment by snitchjinx** [comment]
There is another part of code that I don't quite understand:
in [main.py](https://github.com/alonrubintec/3DViewer/blob/d30bc2da629944b715a7823515fab56fda5b7391/main.py#L63), why it is feasible to pass attributes such as "self.obj_path_label" before it exists?
Would you mind explain this a bit?
Thank you for your consideration!

**Comment by alonrubintec** [comment]
self.obj_path_label is part of the UI file, this variable gets generated when the ui file is loaded.

In QT frameworks, when you load a UI file (often with a .ui extension), it typically contains the definition and layout of the user interface elements (like labels, buttons, text fields, etc.)
