### ISSUE TITLE
Reading point clouds .ply

### ISSUE THREAD

**Issue by bgpantojar** [alonrubintec/3DViewer#3]
Hello,

Very nice app. I was wondering what I should modify to be able to read also point cloues as .ply files. I tried to open one and gave me an error.

Thanks in advance,

Bryan

**Comment by alonrubintec** [comment]
Hello Bryan,

Thank you for your kind words about the app.

Regarding your query, I don't have direct experience with point cloud, but if I had to guess, to read and visualize point clouds as .ply files, you'd need a mechanism to interpret the point cloud data distinctively, as compared to mesh data.

The current application is designed to visualize meshes and not point clouds. Point clouds and meshes differ significantly in their data structures. While meshes are made up of vertices, edges, and faces, point clouds are simply a collection of data points in a 3D space.
